In [1]:
%pwd

'/Users/anilkumar/Desktop/Deepanshu PrEP/Projects'

In [2]:
print("Hello World")

Hello World

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [4]:

conn = sqlite3.connect('customer_churn.db')

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)

for table_name in tables['name']:
    df = pd.read_sql(f'SELECT * FROM "{table_name}"', conn)
    safe_name = table_name.replace(' ', '_').replace('-', '_')
    globals()[f"df_{safe_name}"] = df
    print(f"Created dataframe: df_{safe_name}")

conn.close()

# pulling out the tables from the database (cusomter_churn) and then creating the tables or dataframe using sqlite3
# use pragma command for getting the information for all the tables present in the dataset and their corresponding colums

Created dataframe: df_db_customer
Created dataframe: df_db_subscription
Created dataframe: df_db_support

In [ ]:
# Data cleaning

In [20]:
df_db_customer.head(10)

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None
5,0013-MHZWF,durga,NaN,Delhi,Women,1988-12-10 00:00:00,NaN,None
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00,NaN,None
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00,NaN,None
8,0015-UOCOJ,maya,NaN,Kathmandu,Women,1985-07-07 00:00:00,NaN,None
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00,NaN,None

In [21]:
df_db_customer.tail(10)

,customerid,name,country,state,gender,dob,interests,pincode
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00,NaN,None
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01 00:00:00,NaN,None
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00,NaN,None
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00,NaN,None
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00,job,None
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,NaN,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,NaN,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,NaN,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,NaN,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,NaN,None

In [19]:
df_db_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     str
 1   name        21 non-null     str
 2   country     18 non-null     str
 3   state       21 non-null     str
 4   gender      21 non-null     str
 5   dob         21 non-null     str
 6   interests   4 non-null      str
 7   pincode     0 non-null      object
dtypes: object(1), str(7)
memory usage: 1.4+ KB

In [ ]:
# (a)  rename_col - name 
# (b)  droping the interst and pincdoe column, I don't think both are usefull here 
# (c) dob's datatype (I have to change as it is object)
# (d) in the gender colums (see Men, Male, Women, .......)
# (e) fix missing values in country

In [36]:
# (a)
# df_db_customer.rename(columns = {'name': 'customer_name'})
# df_db_customer.rename(columns = {'name': 'customer_name'}).head(5)
# df_db_customer
df_db_customer.rename(columns = {'name': 'customer_name'},inplace = True)
df_db_customer.head(5)

,customerid,customer_name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [72]:
# (b)
# df_db_customer.drop(df_db_customer.columns[-2:],axis=1)
# df_db_customer.drop(columns=df_db_customer.columns[-2:])
# df_db_customer.drop(columns = ['interests','pincode'],inplace= True,errors='ignore')
df_db_customer.drop(columns = ['interests','pincode'],errors='ignore').head(5)
# columns name in square bracket
# df_db_customer = df_db_customer.drop(columns=['interests','pincode'],errors = 'ignore')

   customerid customer_name country        state  gender                  dob
0  0002-ORFBO        keshav   India  Maharashtra    Male  1982-04-12 00:00:00
1  0003-MKNFE        raghav   India    Karnataka    Male  1995-11-23 00:00:00
2  0004-TLHLJ        lalita   India        Delhi  Female  1978-02-15 00:00:00
3  0011-IGKFF         mohan   India     Nagaland    Male  2001-08-30 00:00:00
4  0013-EXCHZ          mira   India        Delhi  Female  1990-05-05 00:00:00

In [120]:
df_db_customer.head(5)

   customerid customer_name country        state  gender        dob
0  0002-ORFBO        keshav   India  Maharashtra    Male 1982-04-12
1  0003-MKNFE        raghav   India    Karnataka    Male 1995-11-23
2  0004-TLHLJ        lalita   India        Delhi  Female 1978-02-15
3  0011-IGKFF         mohan   India     Nagaland    Male 2001-08-30
4  0013-EXCHZ          mira   India        Delhi  Female 1990-05-05

In [119]:
conn = sqlite3.connect('customer_churn.db')
df_db_customer = pd.read_sql('SELECT * FROM "db_customer"', conn)   # use  actual table name
conn.close()

# (a)
df_db_customer = df_db_customer.rename(columns={'name': 'customer_name'})
# (b)
df_db_customer = df_db_customer.drop(columns=['interests', 'pincode'], errors='ignore')
# (c)
df_db_customer['dob'] = pd.to_datetime(df_db_customer['dob'])

df_db_customer.info()     #  now show all columns

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     str
 1   customer_name  21 non-null     str
 2   country        18 non-null     str
 3   state          21 non-null     str
 4   gender         21 non-null     str
 5   dob            21 non-null     datetime64[us]
dtypes: datetime64[us](1), str(5)
memory usage: 1.1 KB

In [122]:
df_db_customer['gender'].unique()

<StringArray>
['Male', 'Female', 'Women', 'Men']
Length: 4, dtype: str

In [125]:
df_db_customer['gender']= df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

In [127]:
df_db_customer.head()

   customerid customer_name country        state  gender        dob
0  0002-ORFBO        keshav   India  Maharashtra    Male 1982-04-12
1  0003-MKNFE        raghav   India    Karnataka    Male 1995-11-23
2  0004-TLHLJ        lalita   India        Delhi  Female 1978-02-15
3  0011-IGKFF         mohan   India     Nagaland    Male 2001-08-30
4  0013-EXCHZ          mira   India        Delhi  Female 1990-05-05

In [129]:
df_db_customer[df_db_customer['country'].isna()]

    customerid customer_name country      state  gender        dob
5   0013-MHZWF         durga     NaN      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya     NaN  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra     NaN  Telangana  Female 2004-12-01